version: '3'

services:

  dentist:
    build: dentist
    ports:
      - "8083:5001"
    networks:
      - myNetwork

  timeslot:
    build: timeslot
    ports:
      - "8084:5002"
    networks:
      - myNetwork

  chatbot:
    build: chatbot
    ports:
      - "8085:5003"
    networks:
      - myNetwork

networks:
  myNetwork:
    driver: bridge
